server.port: 8090
cloud.aws.credentials.accessKey:
cloud.aws.credentials.secretKey: 
cloud.aws.credentials.instanceProfile: false
cloud.aws.region.static: us-east-1

sqs.queue: test-queue
sqs.queue.event: test-event-queue
sqs.queue.sns.fanout: test-queue-sns
sns.topic: test-topic

localstack:
  sns:
    url: http://localhost:4575
  sqs:
    url: http://localhost:4576

spring:
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
    host: localhost
---

spring.profiles: prod
cloud.aws.credentials.instanceProfile: true
